# Generated by Django 5.0.7 on 2024-07-18 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="banner",
            field=models.FileField(upload_to="banners/"),
        ),
        migrations.AlterField(
            model_name="song",
            name="song_file",
            field=models.FileField(upload_to="music/"),
        ),
    ]
