# Generated by Django 5.0.7 on 2024-07-23 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0005_playlist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playlist",
            name="song",
        ),
        migrations.AddField(
            model_name="playlist",
            name="song",
            field=models.ManyToManyField(to="music.song"),
        ),
    ]
